### PR TITLE
Update feedback to point to the discussion forum

### PR DESCRIPTION
**Pull request by harrietgrace**
Bringing the site in line with the new info on the feedback repo, it now points to the forum ✨

### CODE REVIEW

**Comment by toolmantim** [comment]
Nice! How does it layout/look on desktop/mobile?

**Comment by toolmantim** [comment]
This is where Percy.io would be super handy!

**Comment by toolmantim** [comment]
I just checked it out locally! I updated the URL to post to the "Features" forum (whoops, perhaps that was mis-named originally)… and also changed the button title:

image

What do you reckon about "Post a Topic" instead of "Create a Topic" — the Discourse submit button is "Create Topic", but I think people understand "Post to the forum" as a concept more?

**Comment by toolmantim** [comment]
What do you reckon @harrietgrace?

**Comment by harrietgrace** [comment]
Oop sorry this fell off my radar. Looks great! I think Post is better 👍🏻

**Pull request merged**
