### PR TITLE
Add Head of Marketing

### PR DESCRIPTION
**Pull request by toolmantim**

### CODE REVIEW

**Comment by toolmantim** [comment]
@lachlanhardy I copied the other page over the top, and also removed the application process because it's not true for this role — it'll be an email only situation.

**Comment by lachlanhardy** [comment]
@toolmantim Cool. I'll kill my other PR etc

**Comment by toolmantim** [comment]
@lachlanhardy cool cool! I also noticed a bug — we don't have any `Link` tag on the `LinkedList` links, so they're not doing any front-end routing and the page does a full reload to browse from careers to role, or between roles. Same for the `TextLink` component.

**Comment by toolmantim** [comment]
(our `Link` component wraps the `next/link` component, which does all the routing — it doesn't have any styles though, you can just add it around any `a` tag, put the `href` on the `Link`, and it'll pass through the `href` attribute down on the inner `a` tag)

**Comment by lachlanhardy** [comment]
Eep. Good catch!

I remember making the `TextLink` component cause I had some issue with the `Link` component but 

Have you fixed that already or shall I do it now?

**Comment by toolmantim** [comment]
Cool, nah I haven't done any fixes. Just need to make sure we have a `<Link>` around any `a` tags anywhere!

**Comment by lachlanhardy** [comment]
I’ll sort it.

On Thu, Oct 24, 2019 at 14:38, Tim Lucas <notifications@github.com> wrote:
Cool, nah I haven't done any fixes. Just need to make sure we have a <Link> around any a tags anywhere!

**Pull request merged**
