### PR TITLE
Switch to ECS Deploy Plugin

### LINKED ISSUE #422: Switch to Buildkite ECS plugin
We've ended up in a pickle where we can't really use the [Buildkite ECS plugin](https://github.com/buildkite-plugins/ecs-deploy-buildkite-plugin) to replace:
https://github.com/buildkite/site/blob/master/scripts/deploy-ecs

I wonder what it'd take to be able to use it?

@patrobinson do you have any feels for what we need, vs how you're using it?

### PR DESCRIPTION
**Pull request by toolmantim**
Closes #422

### CODE REVIEW

**Comment by toolmantim** [comment]
image

🤔 any ideas @sj26 @lox?

**Comment by sj26** [comment]
Plugins are specifically disallowed on bastion's deploy agent, because it has superpowers so is super locked down. Can we enable plugins without enabling command eval? Can we whitelist the plugins to only allow the ecs deploy plugin at certain tags?

**Comment by toolmantim** [comment]
I also wondered if we could do a fixed list of allowed plugins, ala:
https://github.com/buildkite/buildkite-allowed-plugins-hook-example

Or `buildkite-plug-ins/*`? (No 3rd party plugins)

Another alternative is to figure out a way to have an agent that just has access to do the required ECS calls (there’s an IAM example in the readme), and move away from using this particular agent. It’s a pattern that Elastic CI Stack people need to deal with often anyway!

**Comment by lox** [comment]
@toolmantim I could pretty quickly create a `--enable-vendored-plugins` and we could vendor it, or we could collab on https://github.com/buildkite/agent/pull/1025?

**Comment by toolmantim** [comment]
Getting https://github.com/buildkite/agent/pull/1025 over the line would be awesome! But I would also love to know what someone is meant to do when they want to deploy from the elastic stack, and give that a go?

**Comment by lox** [comment]
> But I would also love to know what someone is meant to do when they want to deploy from the elastic stack, and give that a go?

I'm not entirely sure what you mean here 🤔

**Comment by toolmantim** [comment]
I was wanting to figure out what people would do if they didn't have a bastion, and were using the elastic CI stack. But let's not go down that rabbit hole… let's just get https://github.com/buildkite/agent/pull/1025 going!

**Pull request merged**
