### PR TITLE
Shopify provided some edits for the case study

### PR DESCRIPTION
**Pull request by lox**

### CODE REVIEW

**Comment by lox** [comment]
I'm a bit worried the quote will be too long. I will check it out.

**Comment by lox** [comment]
image

Am I allowed to tweak the font size on the testimonial @ticky?

**Comment by ticky** [comment]
Yeah, just be aware it’ll affect both of them.

**Comment by lox** [comment]
I shortened the testimonial to fit, I will confirm with JML.

**Comment by toolmantim** [comment]
@lox ready to merge?

**Comment by lox** [comment]
🚢

**Pull request merged**
