### PR TITLE
Add the Docker screencast

### PR DESCRIPTION
**Pull request by toolmantim**
- [x] Add the video with poster frame and page
- [x] Update the description
- [x] Update the docs links

### CODE REVIEW

**Comment by toolmantim** [comment]
Yep, just the related docs @harrietgrace! 😊

**Comment by toolmantim** [comment]
🕺🏼

The `br` tag helps lay out the paragraph for desktop widths, and the `maxWidth` attribute makes it disappear on small screens. Did it look like it needed it?

**Comment by harrietgrace** [comment]
I thought it looked alright as it was, but it could totally have a `<br>` before 'and' if you thought it would be neater. 

image

**Comment by harrietgrace** [comment]
Oh also, what do you think about making the title 'Docker with Buildkite' or something similar? It looks a bit odd just with 'Docker'.

**Comment by toolmantim** [comment]
I reckon just "Docker" instead of "Docker with Buildkite" is probably better… only because we probably want to add a bunch more screencasts and if you scan the list of them, it's probably better to be terse. Even though as a standalone page it's a bit lonely with one word.

I got a chance to boot this up locally properly, and did some edits. In the spirit of "See how Buildkite works in production, with this series of short videos." I thought we should avoid saying "introduction" because it's meant to be jumping into a live, close-to-production setup. So I went with something more along the lines of the stuff people are wanting to do with Docker "build, test + deploy". And I put that `<br>` linebreak in for desktop-sized screens.

Do you think it should be "Docker images" rather than "Docker applications"? Because I don't think people say "Docker Applications" — it might be a NodeJS application, but they build a Docker image for easy test + deployment.

**Comment by harrietgrace** [comment]
We could say 'applications using Docker'? But 'Docker images' would also work 👍🏻

I like the new description! In that vein, should we update the Parallelism description to remove 'introduction to' as well?

**Comment by toolmantim** [comment]
Aight, I think this is ready! 🙌🏼 Imma gonna merge on green! 🚀

Yeah, I reckon it's probably a good idea to update the Parallelism one 👌🏼

**Comment by toolmantim** [comment]
I’ll let you changelog @harrietgrace!

**Pull request merged**
