### PR TITLE
Upgrade to Next 6

### PR DESCRIPTION
**Pull request by toolmantim**
This updates us to [Next 6](https://zeit.co/blog/next6), and switches out the asset babel hacks with universal webpack. It also gives us Babel 7 🎉 I've tested the new long expires and asset hashing code with `NODE_ENV=production`, and it seem to work okay 👌🏼

- [x] Deps
- [x] Replace images and `transform-assets` with webpack file-loader
- [x] Unbreak

### CODE REVIEW

**Comment by ticky** [comment]
I’d been holding out on upgrading because next rather alarmingly inflated the bundle size. Does this still occur?

**Comment by ticky** [comment]
Yeah it looks like it’s gotten even worse; over 700k when current master is ~550k. I’m not sure I’m a fan of next at all anymore.

**Comment by toolmantim** [comment]
I haven’t checked it out yet.

I did some digging on this previously tho, and wasn’t as bad as we initially thought:
https://github.com/buildkite/site/pull/107

But I’ll give it a thorough check today.

**Comment by toolmantim** [comment]
Looks like it's hardly changed from our current master, which hardly changed from Next.js v4 also.

I think previously the total size calc of webpack bundle analyzer was wrong. Most of the JS is only loaded as needed, on demand. I don't think it's *too* bad.

**Comment by toolmantim** [comment]
I'm going to merge! I tried optimising our bundle even more, by ensuring that the `components` don't show up in the dynamic bundles for each page. But I couldn't get either of the below to make a difference to how those pages were bundled:

```js
    // Let's ensure that all our ./components get included in main.js, rather
    // than having some exist in some of the lazy loaded page js chunks
    config.plugins.push(new webpack.optimize.CommonsChunkPlugin({
      name: "components",
      filename: "static/commons/components-[chunkhash].js",
      minChunks: function(module, count) {
        return module.resource && module.resource.includes('/components/') && count >= 0
      }
    }))
```

```js
    // Let's ensure that all our ./components get included in main.js, rather
    // than having some exist in some of the lazy loaded page js chunks
    config.plugins.push(new webpack.optimize.CommonsChunkPlugin({
      name: "components",
      async: true,
      children: true,
      minChunks: function(module, count) {
        return module.resource && module.resource.includes('/components/') && count >= 0
      }
    }))
```

**Pull request merged**
