### PR TITLE
Add James and Paul

### PR DESCRIPTION
**Pull request by toolmantim**
- [x] New photos
- [x] Pick outline colours
- [x] Check links

### CODE REVIEW

**Comment by toolmantim** [comment]
@yob @pda you pick whatever circle colour you want, and links too

**Comment by yob** [comment]
The links look good, and I've chosen a colour.

Ben has lined up time to take a photo tomorrow, so I'll have that ready soon too.

**Comment by toolmantim** [comment]
Hrmm, why didn't the Linc preview update? Booo. I'll just merge and you can check it out on prod @yob and @pda!

**Comment by yob** [comment]
Looks great!

**Comment by pda** [comment]
🎉

**Pull request merged**
