### PR TITLE
Fix whitespace for LinkList chevron

### PR DESCRIPTION
**Pull request by lachlanhardy**
The padding and the positioning were the same size, so any LinkList
item long enough will run into the chevron. This commit increases the padding on the right so that no longer happens.

### CODE REVIEW

**Comment by toolmantim** [comment]
Nice one!

Instead of moving the chevron, could we just ensure there's a bit more space to the left of it so the text wraps properly, because even now it's a bit too close:

image

Wrapping it probably looks AOK?

image

**Comment by toolmantim** [comment]
In that last screenshot, I didn't move the chevron back in the original position, I was just trying to demonstrate that wrapping looks okay. My preference is to keep the chevron position we had, but just be more aggressive on the line wrapping + padding between text and chevron? If that's feasible. The new chevron position doesn't quite feel right.

**Comment by lachlanhardy** [comment]
Sure thing!

On Tue, Feb 4, 2020 at 7:19 PM, Tim Lucas <notifications@github.com> wrote:
In that last screenshot, I didn't move the chevron back in the original position, I was just trying to demonstrate that wrapping looks okay. My preference is to keep the chevron position we had, but just be more aggressive on the line wrapping + padding between text and chevron? If that's feasible. The new chevron position doesn't quite feel right.

**Comment by lachlanhardy** [comment]
@toolmantim I've switched that out. How do you like it now?

**Pull request merged**
