### PR TITLE
Make changes that REA requested

### PR DESCRIPTION
**Pull request by lox**
This makes some updates to the REA case study.

The images need some cropping, what is the best way to do this @ticky? 

screenshot

### CODE REVIEW

**Comment by toolmantim** [comment]
Wanna update the PR so it’s the words and one of the photos Lox? And we can ask em for a vertical one?

**Comment by lox** [comment]
Yup, I guess 🤷🏼‍♂️

**Comment by lox** [comment]
I'm already pushing my luck with Tomas, so I might have to get creative somehow.

**Comment by ticky** [comment]
Whoa, why’d you close it? Doesn’t it just need some changes?

**Comment by lox** [comment]
Imma put the copy in another one and we can re-introduce the photos later, I've got a Shopify one coming up in a few seconds too.

**Pull request closed without merging**
