### PR TITLE
Disallow touch zoom on Dropdown components

### PR DESCRIPTION
**Pull request by ticky**
This prevents the iOS default zoom behaviour on our About page portraits if you tap between them too quickly. It only disallows repeated taps on the same portrait, however.

### CODE REVIEW

**Comment by ticky** [comment]
Note that I’m _only_ turning this off for the element that triggers the dropdown. You can still tap zoom on things outside the dropdown, and the things inside the dropdown’s popover. I think it’s a reasonable compromise! (And avoids me having to add state directly to the Person object, haha)

**Comment by toolmantim** [comment]
Yeah totally! I think so too.

**Comment by ticky** [comment]
Vaguely on the topic, I’d really like to backport the Dropdown changes from Site to Frontend, someday…!

**Comment by toolmantim** [comment]
And even use the Dropdown for the mobile menu too 😱

**Comment by ticky** [comment]
That might not directly apply, but the technology here is definitely applicable. I think it’ll just require a bit more of a considered update. :)

**Pull request merged**
