### PR TITLE
Switch to Puppeteer 1.5.0

### PR DESCRIPTION
**Pull request by toolmantim**

### CODE REVIEW

**Comment by rarkins** [comment]
Did Renovate miss this one?

**Comment by toolmantim** [comment]
Yeah @rarkins, it never tried to pin the second FROM. It’s a multi-stage build, so makes things a little trickier on the  Renovate side perhaps?

**Comment by rarkins** [comment]
We actually can handle multi-stage builds OK, I think it's just because it's on adjacent lines and my regex needs a small fix to allow that.

**Comment by rarkins** [comment]
I found the bug and have fixed it. It should be rolled out live later today so from now on you should get this puppeteer version updated by Renovate.

**Comment by rarkins** [comment]
@toolmantim FYI, this Docker pinning PR (https://github.com/buildkite/site/pull/137) will get autoclosed once you merge this PR. It's been raised because Renovate now correctly detects adjacent FROM lines.

**Comment by toolmantim** [comment]
I noticed that you handle multi-stage builds in another repo, just after I posted the comment here 🙊

That's awesome it's been fixed! I was wondering what was going on, once I saw it working okay elsewhere. 🎉

**Pull request merged**
