### PR TITLE
Replacing deprecated `static` directory with `public`

### PR DESCRIPTION
**Pull request by lachlanhardy**
Upgrading as per build warnings and https://nextjs.org/docs/basic-features/static-file-serving

We do some funky stuff though so this first pass may not cut it.

### CODE REVIEW

**Comment by toolmantim** [comment]
Oh yeah, we've got the asset timestamping thing via babel — that might need updating too?

**Comment by toolmantim** [comment]
Or maybe not? 🤔

**Comment by lachlanhardy** [comment]
The simplest change is just moving the static folder inside the public one. It only contained the favocon anyway. That’s done
the more complex version involves working out time stamps and URLs. I’ll try that again tomorrow
On Wed, Jan 22, 2020 at 5:37 PM, Tim Lucas <notifications@github.com> wrote:
Or maybe not? 🤔

**Comment by toolmantim** [comment]
Makes sense! 👍🏼

**Pull request merged**
