### PR TITLE
Extract role pages into careersPage component

### PR DESCRIPTION
**Pull request by lachlanhardy**
Technically, this is mergeable. But it's not pretty yet!

This extracts the separate role details into a data file in `lib` and delivers via a component that's effectively a Layout.

### CODE REVIEW

**Comment by toolmantim** [comment]
Hey! I did a bunch of work on this branch today, but I’m not sure we did the right thing with the case studies and screencasts actually… rather than just composing React components. But I’d be keen to talk it through on Zoom, because I could go either way.

**Comment by lachlanhardy** [comment]
@toolmantim No issues with moving to a new paradigm. There are definitely issues with this one, but I was trying to model the existing structures to make the app easier to understand.

Not that I necessarily have a better idea in mind!

Happy to discuss.

**Comment by lachlanhardy** [comment]
We decided on a completely different approach which @toolmantim implemented here: https://github.com/buildkite/site/pull/536

Basically, we agreed we were getting too fancy and we've dropped back to something easier to reason about.

Closing this, never to be spoken of again.

**Comment by toolmantim** [comment]
I will also go and quietly remove my WIP branches 😁

**Pull request closed without merging**
